# Generated by Django 5.1.5 on 2025-04-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_count__gt", 0)), name="stock_gt_0"
            ),
        ),
    ]
